version: '3.8'
services:
  login_service:
    build: .
    ports:
      - "5055:5055"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URI=postgresql://neondb_owner:Od9UnVJ2Wvfr@ep-rapid-lake-a8yqbhfk.eastus2.azure.neon.tech/neondb?sslmode=require
      - DEBUG_MODE=true
      - DB_USER=neondb_owner
      - DB_PASSWORD=Od9UnVJ2Wvfr
      - DB_HOST=ep-rapid-lake-a8yqbhfk.eastus2.azure.neon.tech
      - DB_NAME=neondb
      - DB_SSLMODE=require
      - JWT_SECRET_KEY=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - .:/app
    command: ["python", "app.py"]
    
  redis:
    image: "redis:7.0"  # Use the Redis 7.0 image
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]